import {
  DEFAULT_FILTER_CUTOFF,
  DEFAULT_FILTER_DCUTOFF,
  IMAGE_DEFAULT_FILTER_BETA,
  IMAGE_DEFAULT_WARMUP_TOLERANCE,
  IMAGE_DEFAULT_MISS_TOLERANCE
} from '../../libs/shared-config.js';

export {
  DEFAULT_FILTER_CUTOFF,
  DEFAULT_FILTER_DCUTOFF,
  IMAGE_DEFAULT_FILTER_BETA as DEFAULT_FILTER_BETA,
  IMAGE_DEFAULT_WARMUP_TOLERANCE as DEFAULT_WARMUP_TOLERANCE,
  IMAGE_DEFAULT_MISS_TOLERANCE as DEFAULT_MISS_TOLERANCE
};

export const PROJECTION_NEAR = 10;
export const PROJECTION_FAR = 100000;
export const PROJECTION_FOVY = 45.0 * Math.PI / 180;

