export const DEFAULT_FILTER_CUTOFF = 0.001;
export const DEFAULT_FILTER_DCUTOFF = 0.001;

export const IMAGE_DEFAULT_FILTER_BETA = 1000;
export const FACE_DEFAULT_FILTER_BETA = 1;

export const IMAGE_DEFAULT_WARMUP_TOLERANCE = 5;
export const IMAGE_DEFAULT_MISS_TOLERANCE = 5;

